# Generated by Django 5.0.6 on 2024-06-25 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_mascotas_salvadas_remove_alimentos_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alimentos',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='juguetes',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salud',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='alimentos',
            name='idAlimentos',
            field=models.CharField(default=0, max_length=10, primary_key=True, serialize=False, verbose_name='Id alimentos'),
        ),
        migrations.AlterField(
            model_name='juguetes',
            name='idJuguetes',
            field=models.CharField(default=0, max_length=10, primary_key=True, serialize=False, verbose_name='Id jueguetes'),
        ),
        migrations.AlterField(
            model_name='salud',
            name='idSalud',
            field=models.CharField(default=0, max_length=10, primary_key=True, serialize=False, verbose_name='Id Salud'),
        ),
    ]
