# Generated by Django 5.0.6 on 2024-06-26 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_boleta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimentos',
            name='precio',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='juguetes',
            name='precio',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='salud',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
